### ISSUE TITLE
Can we still have an Apache license if we make use of rasa x?

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#15]
Rasa x is layer on top of open source rasa that we might use, the question is whether this changes the intended permissive Apache 2.0 license of our open source project?

See [rasa x license](https://00f74ba44be8fdceb7da37d7e47f6a2cf8e0523c9e-apidata.googleusercontent.com/download/storage/v1/b/rasa-x-releases/o/rasa_x_ce_license_agreement.pdf?jk=AFshE3X5R7tjmi2D5r30nKb3L8jgA-to1swowx4JOj0O5644BkJIe17tuKIi-z38YTjGJBZsGSuHcK1MrhP8ldWGFy8NtAnRlgJgmctCZZlBZw-lzY-RbrSHHIJPD0vg3pAgUgP5ooS_Bznryz_erbSfk4M49UxAa-cSgWO2Nukga__3C0d3AP8w71PYoOtWbiMS00a9Q9cWJNM7zaNs0ZSQekmwfsRfVjtIldJ0gDvmjb8OoDK4Zn0VtqRGNNY1kNdfe2SaCqUblV3IVJSYJ_Bt0SQXnw-Jbhu9WXWkOdGvjm-wn4W9OiDufRqjgvDkgSCC1PWAQteaxJ-xcGyyXvRhGxtfCOxJ3GZR3WIa_Hb52nXDPom3xrsioH84_l0FdQbr0cdDwYpoPIIIx3mNWo8hXZT6sLMAfhQkhsIRr-UyMWVJsXJUl_hw_C-2d7l-h1NnQhm68XASWlqH_PwXRb7nQk0WURVsGbBHNSbmrzqnUappB9zrM86oLL2dbld4yGr4d8Bw0lDVTk4WbyAWnt7Ye6lrWlj3Xre_K4OK5_w8IaBO72FzLmLvyhhPRQZYt08y69PHsMI8mXWMHOTpDAQBNI9moz31pV0O1gvei70aBtOLfRhgurU9j3iQgQlRf1cjIlSatUvSDkBB3TZZAYWOXWVULqXcBBP0ZNWWGqszm1UdIrz1mxT7fvSClkiGQ6Y4nLr8qAhTjkXXIoyJxxB3BW319smG5uLxLvg1fe1sNS0zAeTp0-aDgU3l7m32xxSjTgk04a1FfYwkFbk75sNtFrOPpQgyOsUT1BE9Y3ZWY-mo-XBEplY0zQEob-GO7qMflO3pVBA_30V09XyLIV_a9vJlzDZG8Yipmk2u-4-MpmhXt6DA_3YIjStkntbGHP-A3H-09pyLyVFpF2rKVkp0TVITBHd8Pq9Ps1zd2frwIKAWqt0fzfmHAY1JvGeE8U938FXx9SqQ8A6W7R03uLw4Hp5FbfEt&isca=1)

The part under SAAS and No Other Rights worries me. I think in practice this is not gonna be problem for our project, but I guess we need to include this in the license of our project if a component of our project is running rasa x? How should I read this?

**Comment by svenvanderburg** [comment]
@LourensVeen what do you say?

**Comment by LourensVeen** [comment]
The link above appears to point to a cached copy which has since expired. This seems to be better: https://storage.googleapis.com/rasa-x-releases/rasa_x_ce_license_agreement.pdf

To start with, in general we would like to not use non-Open Source software, because it goes against the principles of Open Science and FAIR. So please consider whether you really need Rasa X. If you do, read on.

The license says that "Any noncommercial purpose is a Permitted Purpose." I'm not sure about commercial partners in this project, but as long as you're doing science with public money and no one is trying to get a profit from this, you're good to go. It follows with "Any commercial purpose not restricted below is a Permitted Purpose.", so the SAAS and No Other Rights sections only apply to commercial use.

The SAAS section restricts commercially offering a service that competes with Rasa, i.e. offering a platform for enterprise-grade virtual assistants as a service. You're not doing that, you're just making a single assistant for a particular purpose.

The No Other Rights section is just a backstop which says that any rights not mentioned in the license aren't licensed. You cannot sublicense the code, which means that everyone using the code needs to get a license directly from Rasa Technologies, Inc., and cannot get one from you. This is all just some technical infrastructure, the GPL actually works the same way.

I'm not really sure how you would use Rasa X. Would you end up distributing it with your software? Or installing it on a server to use in your experiments?

**Comment by svenvanderburg** [comment]
* Agreed that we should try not to use it
* Indeed for our usecase we are fine since we are not commercial
* We would indeed install it on a server or locally to serve the chatbot, and probably the scripts/docker image to install rasa x are distributed with our software.

So I understand it correctly that it's then the person cloning our repo's responsibility to check whether he follows the rasa x license even though we might install it in a script or docker image as a dependency for our software.

**Comment by LourensVeen** [comment]
Hm, I think I missed your April 28 reply, there was something wrong with my mail filtering that caused some missed notifications.

So to answer that last bit, you can redistribute Rasa X, you just have to make sure that you include a copy of the Rasa X license, and you should point out clearly that there's non-open source software included so that your users know to check it.

I guess there's potentially an issue if the makers of Rasa X ever decide to make a virtual coach themselves, in which case no one else could do that anymore at least commercially.

**Comment by svenvanderburg** [comment]
Cool, thanks for the clarifying reply @LourensVeen! This is really useful. (sorry for closing the issue prematurely I was on a rambling organisatory frenzy.

**Comment by LourensVeen** [comment]
No worries. Actually, I should probably tag @RvanNieuwpoort on this.
