### ISSUE TITLE
Future-self dialog improvements from demo 21-03-2022

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#224]
We demoed the future-self dialog on 21st of march and came up with some improvements:

- [x] For the rescheduling query: also include option for in an hour. And make it dynamic depending on the time of day.
- [x] For the question about what kind of smoker (i.e. smoker, non-smoker, etc.) Add a 4th option: other. And ask people to specify further if they mention 'other'. Vice versa for moving-related question.
- [x] The first time we ask an open question we specify why we store the answer.

**Comment by nelealbers** [comment]
We (Sven and I) decided to address the third point at a later stage when we have a better idea of what the intervention looks like, see [this issue](https://github.com/PerfectFit-project/virtual-coach-issues/issues/229).

We decided to not implement the second point due to the resulting complexity of the stories and the decrease in user-friendliness.
