### ISSUE TITLE
Investigate deterministic alternatives to Rasa 

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#250]
In the current design, the conversation runs into deterministic and closed steps. The user is asked to answer with defined text, and the VC replies with predefined sentences. In such configuration, adopting an AI solution as Rasa is could produce unnecessary complexity (i.e., difficulties in controlling the flow) without providing added value. 
An alternative could be to implement the dialogs logic ourselves and attach it to the broker directly.

The two approaches should be evaluated and compared, in order to decide whether switching from Rasa to a fully deterministic implementation would be convenient.

**Comment by svenvanderburg** [comment]
Also, there might be other frameworks than rasa that fit our case better.

**Comment by svenvanderburg** [comment]
See https://github.com/JStumpp/awesome-chatbots
See [Choosing a Chatbot Development Tool](https://www.miso.es/pubs/IEEE_SW_BotPlatforms.pdf)
# Options

## Fully custom implementation
I haven't found any good examples of people implementing a chatbot that is similar to our case. There are tutorials like [How to make a rule-based chatbot in python using flask](https://python.plainenglish.io/how-to-make-a-rule-based-chatbot-in-python-using-flask-d5649a6ce308). But they all serve as demos and will definitely not make a mature product.

### actions.py
It would still be nice to have a separate module with all the actions, but we don't need to run a separate actions server. All the functional code can be reused easily.

### A web server
We can make use of a very simple flask API with 2 endpoints: a POST request_response method and a POST trigger_conversation method. To facilitate a trigger_conversation method we also need an outgoing request to the broker.

### Tracker store and keeping track of context
Multiple conversations are going on at the same time. We need to keep track of where users are in the conversation, and provide a sort of context for the user message. This can be a simple sqlite database, with one table storing the user id and corresponding state id. This is probably the most difficult thing to do right.

### Finite state machine
The dialog logic that we need can be represented as a [finite state machine](https://en.wikipedia.org/wiki/Finite-state_machine). Upon input from the user we:
1. Check the current state of the user
2. Transition to the next state based on the current state and the user input
3. Return the bot response according to the state transition

See https://www.hamidadelyar.com/blog/finite-state-machine-chatbot/

The success of a custom approach stands or falls with a good design for coding up the dialogs, so I expect quite some effort is needed here. Maybe we can have a similar interface as botkit.

**Cons:**
* I will be a lot of work to recreate our own chatbot framework from scratch.
* It will be difficult for other people to extend our chatbot if we are not building it one of the major frameworks.

## Open-source rule-based chatbot frameworks
### [Botkit](https://github.com/howdyai/botkit)
Botkit is an open source developer tool for building chat bots, apps and custom integrations for major messaging platforms. It is completely rule based.

See [their simple way of implementing threaded dialogs](https://github.com/howdyai/botkit/blob/main/packages/docs/core.md#using-dialogs)

**Cons:**
* It is Javascript-based . 


### [Bottender](https://github.com/yoctol/bottender)
Similar to Botkit, also javascript-based.

**Cons:**
* Similar to Botkit, but appears to have smaller community.

See https://www.quora.com/What-are-some-open-source-rule-based-chatbots

## Rasa without machine learning
A big pain with using rasa is having to wait a long time every time we retrain the model, even though we don't really need machine learning. We can try to use rasa without it's fancy ML algorithms.

We can use the most simple pipeline for NLU/intent classification, because we really don't need any intent classification. (we always work around this by doing exact string matching in custom actions).
We can get rid of TEDPolicy and only use AugmentedMemoizationPolicy. See [https://rasa.com/blog/dialogue-policies-rasa-2/](dialogue management). In theory because we do not give the user space to utter something unexpected, we always stay within the specified dialog.

## Non-suitable options

### [Chatterbot](https://github.com/gunthercox/ChatterBot)
ChatterBot is a machine-learning based conversational dialog engine build in Python which makes it possible to generate responses based on collections of known conversations.
**Cons:**
* Not a framework, i.e. no API, tracker store etcetera

### [Microsoft Bot Framework SDK](https://github.com/Microsoft/botbuilder-python)
**Cons:**
* Seems to be build around an Azure service

### [botpress](https://github.com/botpress/botpress)
**Cons:**
* Proprietary
* Mostly GUI-based

### [pandorabots](https://www.pandorabots.com/docs/feature-comparison/)
Pandarabots seems nice, in the sense that it makes use of the open standard AIML (sort of of XML for chatbots). 
**Cons:**
* Service-based

## Conclusion and next steps
We have to choose between:
* Living with the awkward way of defining our simple linear rule-based dialogs in rasa (but see if we can at least get rid of the unnecessarily complicated ML algorithms in the back). Follow-up in https://github.com/PerfectFit-project/virtual-coach-issues/issues/256
* Spend a lot of time creating our own chatbot framework from scratch. We need a proper estimate if we want to go down this route. **This is off the table**
* Move to javascript. Botkit seems perfect for our type of dialogs. But let's investigate how good the fit is if we want to go into this path. Folow-up in https://github.com/PerfectFit-project/virtual-coach-issues/issues/255

**Comment by svenvanderburg** [comment]
To follow up:

* See [this thread](https://github.com/howdyai/botkit/issues/423) on someone (unsuccesfully) requesting botkit for python
