### ISSUE TITLE
Create (re)lapse dialog functionality

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#253]
When a lapse or a relapse has been detected, the user enters in the lapse or relapse phase. In this case, the (re)lapse dialog has to be initiated.
A (re)lapse dialog placeholder has to be created and should be triggered in the (re)lapse phase.

**Comment by BendikC** [comment]
For this issue, we should use a roundabout approach to triggering the dialogs.
We want to send a task to celery so that celery can trigger the task externally, by sending an external trigger back to rasa. This makes the rasa side less cluttered with logic components and makes the structure of the project more understandable. 
We keep the dialogs in the rasa component (as we are working with big dialogs this will be quite big) and the logic is handled by celery. This also allows for more customizability in general for the triggering of this phase.
The way I envision this being done is through a custom action that triggers the celery task, called when the user types in ''help' ,and then for the relapse dialogs in rasa they all start with the external trigger sent by celery and go on normally the way they have been implemented.

**Comment by BendikC** [comment]
Upon further explanation from Kristell, the triggering of the relapse phase is a bit clearer.
The relapse phase should be triggerable in two ways:
 - The "help" command typed in by the user
<sub> This command can be triggered when no input is required or during the execution phase by simply providing the word "help" as the input. If it is triggered in this way during the weekly reflection, the user needs to go back to the reflection so that they can complete it</sub>
- External triggering if the user tracks smoking into their tracker past their planned quit date
<sub> This triggers the lapse phase of the smoking branch outright, instead of what would happen with the other triggering where the user could choose the branch with certain inputs <sub/>
