### ISSUE TITLE
Investigate communication with the scheduler

### ISSUE THREAD

**Issue by BendikC** [PerfectFit-project/virtual-coach-server#265]
For this issue: #249 after each component is finished, we would want to report back to the scheduler that the specific component is finished in order to trigger the next one. 
This could be done through rasa but we prefer to have the scheduler handle most if not all of the actual event logic.

Main idea is: How will we get rasa to interact with our scheduler (sending signals to it)?

**Comment by BendikC** [comment]
## Celery Discussion

From what I'm reading I can't find much to suggest that celery has any built in way of receiving messages from other parts of the project, as its main purpose is task scheduling.

The only thing I've been able to find which seems like it could be relevant is "signals" in celery, which I haven't properly understood myself so it would be nice if someone else took a look at it: https://docs.celeryq.dev/en/stable/userguide/signals.html

## Alternatives

Using a different framework to open up a connection would be a possibility, some sort of long polling situation where we trigger the task and open a connection and wait for a response. Once the dialog is complete we send back a message allowing us to trigger the next one and so forth. Thing to watch out for with this method is that a disconnect message would also be important to send as if they dont complete the dialog and just exit celery still needs to know what is happening.

### How

A promising way to do this would be to use Kombu, a celery sub-project that allows for the sending and receival of messages. 
Documentation: https://docs.celeryq.dev/projects/kombu/en/stable/


____

Another idea is the use of websockets. I'm not sure how they work with python but from my general understanding of them they allow for quite easy communication and message sending between themselves. Might be a bit overkill for the few messages we would be sending, but the disconnect would probably be cleaner.

### How

Not sure how websockets are implemented with python, only ever used them in Node.js. It doesn't seem to complicated as they are built into the python library. 
Seems like django is what people use together with redis (which is what we currently use as our message broker)
See this: https://channels.readthedocs.io/en/stable/

Still think this method is too much and probably overkill, but researched it just to have more alternatives.

___
These ideas are mostly theoretical as I'm not experienced enough to know how these would work within the context of the project itself, let me know if any of these are an impossibility and why, so I could better understand what's happening behind the scenes.

**Comment by svenvanderburg** [comment]
## Triggering a task from external service
We can call `Celery.send_task` from rasa (but we could use it in all our apps) if we configure the `Celery` object pointing to our celery service. [see this SO thread](https://stackoverflow.com/questions/18433071/celery-how-to-send-task-from-remote-machine).

I think it is important to from rasa trigger a celery task that just notifies celery that something happened, instead of in rasa deciding what the next task should be. So all the logic of when what happens is in celery.

## Triggering a task that needs to run later
For scheduling a task to be executed later (but not periodically) we can use `apply_async` with `eta` argument. See [this SO thread](https://stackoverflow.com/questions/57269053/how-to-start-a-task-at-a-specific-time-with-django-celery).

## Alter a periodic task in celery beat
[see SO thread](https://stackoverflow.com/questions/37339649/how-to-dynamically-add-a-scheduled-task-to-celery-beat)

**Comment by svenvanderburg** [comment]
@BendikC I think we can close this right?
