### ISSUE TITLE
Users need to complete self-initiated HRS dialog to continue intervention

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/virtual-coach-server#396]
See here: https://github.com/PerfectFit-project/testing-tickets/issues/25.

- [x] For non-relapse branches, we do not want reminders to complete the HRS dialog if it expires. This also means that people cannot complete the HRS dialog then if it expires, but that is ok.

**Comment by wbaccinelli** [comment]
@nelealbers @aversluis1 @emeijerperfectfit I'm wondering weather we want to let the users access the hrs dialog during the preparation phase or not. Before the goals setting dialog, in particular, it could be a bit tricky. One of the branches (the relapse) asks also to reschedule the quitting date, but they have none set yet. In some other branches they can access the ehbo, while it is not available otherwise before the explanatory video, which is shown even after the goals setting. What do you think?

**Comment by emeijerperfectfit** [comment]
Hi Walter, good idea to remove it from the preparation phase! I think we can’t just disable the help command (because users will think the coach is not responding, if they are just trying out the coach - it will be in the manual that they get) but I think we should send a message like this is they type help in the preparation phase:

Je bent nu in de voorbereidingsfase. Je kunt ‘help’ gebruiken tijdens de uitvoeringsfase

And if possible the current ‘sorry ik begrijp (nog) niet..’ message which the menu should not include the one about ‘help’ in the preparation phase
Would that work to solve this?

Btw I saw that my mother had managed to get the HRS dialog going by typing ‘stop’; so perhaps good to check that only the words that the coach only has an active respons to commands that are included in the menu?

**Comment by wbaccinelli** [comment]
Ok, we will remove the command in the preparation phase. It is also possible to remove it from the list of shown commands during the preparation phase .

We are not checking for single words, but there is natural language processing model that recognizes the commands. We can try to rune it a bit more.

**Comment by aversluis1** [comment]
@Milonvv: see discussion above, so that you know what has changed and the impact this has on the instruction manuel for users.
