### ISSUE TITLE
"Sorry ik begrijp het niet" menu

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/virtual-coach-server#400]
I encountered some issues with this

1. Could we put "verder" for continuing a previous dialog as the first option? I think this might be the one that's used most often. We can then keep the order of the other options the same
2. The menu seems to be triggered too quickly after the profile creation dialog (as Nele mentioned) but I think also after some other dialogs. The unhelpful thing is that I can't remember which ones
3. I think we should rephrase the start of this message (Sorry, ik begrijp (nog) niet wat je bedoelt), it's actually quite annoying if you get 'I don't understand you' all the time. Also Sam won't really try to understand what someone means. I'd suggest to replace the first message by this: 
"Goed om van je te horen! Er zijn verschillende dingen die je kunt doen." [and then show the menu]

**Comment by emeijerperfectfit** [comment]
Last weekend I had two dialogs that were mixed, as I had already typed 'verder' in the menu and the previous dialog was started, but the entire menu was shown as well. Not sure whether this needs to be fixed or people just need to be more patient than I was
![Screenshot_20230722-093719](https://github.com/PerfectFit-project/testing-tickets/assets/135458606/8d067cb6-af8d-4450-95d2-bc526ca87f7a)

**Comment by wbaccinelli** [comment]
@emeijerperfectfit this is due to the delay between one message and the subsequent one. The coach produces all the answers, and then it starts sending them with an imposed delay, but it will still listen to the user anyway and it will respond to new messages. This results in overlapped messages if the user is not patient enough. It's a problem that has no simple solutions (and most probably it has no solutions at all).

**Comment by wbaccinelli** [comment]
points 1 and 3 to be addressed
