### ISSUE TITLE
General activity dialog

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#407]
General activity:
- Time indication (14-18 mins) in general activity dialog does not say much, remove this?
- Bedankt om dat te delen should be Bedankt voor het delen
- We zijn blij dat je deze oefening nuttig vindt. Daarom voegen we hem toe aan je ehbo doos. I prefer: Ik ben blij dat je deze oefening nuttig vindt. Daarom voeg ik hem toe aan je ehbo doos.
- If the user has completed all exercises from a category, the coach should say something about this, or the category should not be offered anymore. See screenshot 7.12 30/7. Now there is an empty menu and the user can only type 1 for another type of exercise 
- If you have already answered the questions about the previous exercise but don't complete the entire dialog, you don't continu where you left off if you resume the dialog (through verder) but you have to do everything over again. I'm not sure whether we want it that way

![Screenshot_20230730-071216](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/74d8bf84-bfff-4d5c-8b0e-8d286a8e3901)

Tester: Eline

**Comment by wbaccinelli** [comment]
A couple of comments:

- The time indication is there because the user can decide to reschedule the dialog. Or at least this is how it has been designed. Shall we remove this? Can we keep this and the small contents changes as low priorities? 
- In agreement with the Kristell [see this issue](https://github.com/PerfectFit-project/virtual-coach-issues/issues/296), we decided that not all the dialogs can be restarted from a point that is not the beginning, because it would have taken a considerable amount of time to implement this, and some dialogs are short enough. So, only the goal setting and the weekly reflection can be resumed from a different state.

**Comment by aversluis1** [comment]
@wbaccinelli , i think it is fine to keep the time indication and to make small content changes as low priorities. 
Understand the decision regarding restarting the dialogs.

**Comment by nelealbers** [comment]
There is also a typo in the menu in the general activity dialog: https://github.com/PerfectFit-project/testing-tickets/issues/56

**Comment by nelealbers** [comment]
> * Bedankt om dat te delen should be Bedankt voor het delen

This formulation is fixed here: https://github.com/PerfectFit-project/virtual-coach-rasa/pull/164

And the typo in the menu as well.

**Comment by nelealbers** [comment]
> * We zijn blij dat je deze oefening nuttig vindt. Daarom voegen we hem toe aan je ehbo doos. I prefer: Ik ben blij dat je deze oefening nuttig vindt. Daarom voeg ik hem toe aan je ehbo doos.

Fixed here: https://github.com/PerfectFit-project/virtual-coach-rasa/pull/169
