### ISSUE TITLE
Duplicate messages?

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#439]
Tester: roxy_van_eersel@hotmail.com

At some moment, Sam started sending me sending me duplicate messages within a minute from each other and kept sending me the same exercise. I did not figure out how to move past this exercise and we never discussed actually quitting smoking (like start date or how much I smoke). 

Further explanation: I suspect something went wrong when I said bye to Sam after an exercise, which he followed up with the standard messages for when he does not recognize what you said. I replied “Verder” to these messages and then I lost track of how the program was supposed to go. The exercise I kept receiving:
 
![image](https://github.com/PerfectFit-project/virtual-coach-issues/assets/118284434/6bb4db8d-d9ba-4a83-8a3b-1c98a3bd843b)

**Comment by wbaccinelli** [comment]
@aversluis1 would it possible to have also a date indication, to trace it back more easily?

As a side note, I think that it would be better organization-wise to open these issues in the [testing-tickets repo](https://github.com/PerfectFit-project/testing-tickets/issues)

**Comment by ghost** [comment]
@wbaccinelli Hi Walter, the date of sending unrecognized messages to Sam was 28 juli at 12:33 and 15:42. 
The duplicate messages started on 29 juli at 12:00 - 12:01, but also occurred for example on 30 juli at 12:00 and 31 juli at 12:00.
Finally, I first did the exercise mentioned above on 31 juli at 8:45 (and multiple times after), and I thought I finished it on 9 august at 10:57, but kept receiving the same exercise.

**Comment by wbaccinelli** [comment]
@rvaneersel thank you for the details, they are very useful! For some reason there was a huge amount of uncompleted general activity dialogs. This should have been solved already, and since yesterday an updated version is running, so this should not happen anymore (but let me know if you experience such behavior again). I am anyway trying to replicate this anyway.

I also fixed all the pending general activity dialogs for you, so now you can continue with the intervention with the verder command.
