### ISSUE TITLE
New quit date isn't triggered for certain users

### ISSUE THREAD

**Issue by BendikC** [PerfectFit-project/virtual-coach-server#483]
There seems to be a bug that happens with some users where they will be stuck in the buffer state instead of execution because the new quit date isn't planned. Sending a new_day event fixed the problem for the users, so we can use this to understand why it is happening:

- [x] Figure out cause of the bug, look into why it only happens for certain users
- [x] Fix
- [x] Add in new release

**Comment by wbaccinelli** [comment]
Maybe not executed because the notify_new_day task fails before reaching all the users. I see that [here](https://github.com/PerfectFit-project/virtual-coach-rasa/blob/b1b69fdcc3af47c33f29835728c9a40d5869395e/scheduler/state_machine/controller.py#L412) can fail in case no quit data has been set, and this happened.
