### ISSUE TITLE
Investigate using gRPC instead of REST for niceday-api

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#81]
Because the only consumer of our niceday REST api is ourselves, we might consider using gRPC instead. According to Stefan it is supposedly simpler than using REST when having internal communication.

AB#2028

- [x] Do a small comparison, results can be in this issue
- [x] Possibly create follow-up tickets

**Comment by raar1** [comment]
OK, I had a quick play around with gRPC, and here's the sort of thing the server/client might look like for fetching a user profile:

Firstly, the `niceday.proto` file defining the services, and request/response types:
```protobuf
syntax = "proto3";

package niceday;

service ProfileService {
  rpc getUserProfile (ProfileRequest) returns (ProfileResponse) {}
}

message ProfileRequest {
  int32 userId = 1;
}

message ProfileResponse {
  map<string, string> userProfile = 1;
}
```

Secondly, `niceday_server.js`, the server which implements the service defined above:
```js
var PROTO_PATH = __dirname + '/niceday.proto';

var grpc = require('@grpc/grpc-js');
var protoLoader = require('@grpc/proto-loader');
var packageDefinition = protoLoader.loadSync(
    PROTO_PATH,
    {keepCase: true,
     longs: String,
     enums: String,
     defaults: true,
     oneofs: true
    });
var hello_proto = grpc.loadPackageDefinition(packageDefinition).niceday;

// Implement getProfile RPC method
function getUserProfile(call, callback) {
  var example_profile = {
    'name': 'Dr Fear',
    'age': 197245,
    'id': call.request.userId
  };
  callback(null, {userProfile: example_profile});
}

// Start server
function main() {
  var server = new grpc.Server();
  server.addService(hello_proto.ProfileService.service, {getUserProfile: getUserProfile});
  server.bindAsync('0.0.0.0:50051', grpc.ServerCredentials.createInsecure(), () => {
    server.start();
  });
}

main();
```

And finally, `niceday_client.js`, the client that requests the user profile:
```js
var PROTO_PATH = __dirname + '/niceday.proto';

var grpc = require('@grpc/grpc-js');
var protoLoader = require('@grpc/proto-loader');
var packageDefinition = protoLoader.loadSync(
    PROTO_PATH,
    {keepCase: true,
     longs: String,
     enums: String,
     defaults: true,
     oneofs: true
    });
var hello_proto = grpc.loadPackageDefinition(packageDefinition).niceday;

function main() {
  var client = new hello_proto.ProfileService('localhost:50051', grpc.credentials.createInsecure());

  client.getUserProfile({userId: 525}, function(err, response) {
    console.log('Fetched profile:', response.userProfile);
  });
}

main();
```

Running all this causes the client to print:
```
Fetched profile: { name: 'Dr Fear', age: '197245', id: '525' }
```

# Some notes
1. What is nice about the above is that you are defining the request and response types explicitly in the API using protobuf syntax. This would likely mean we don't need all the type validation stuff we do in the python client currently due to converting from JSON. That said, almost everything is strings anyway since that's what niceday is returning from its API, so it probably won't matter anyway.
2. This removes the need for all the http request handling that we do explicitly (e.g. with `requests` lib) in the python client currently. That's a positive. It would likely reduce that client to a very thin wrapper around the protobuf stuff.
3. gRPC's improved performance won't matter to us since we are fetching JSON from niceday anyway, and won't be doing streaming. However, for the sensor data api this could be very advantageous.
4. Defining the API in the `.proto` file, or a REST api in `openapi.yml` has a similar amount of boiler plate for our case. I suppose I have a slight preference for the rpc version due to its procedure-centricity.
5. In my quick test above I made a js client, but you can of course make that python.

**Comment by raar1** [comment]
@svenvanderburg Let me know your thoughts on the above and we can see about future steps. In essence I think using grpc gives a small but net benefit in the `niceday-api` case, but could be very advantageous for sensor data services (or anything with streaming, large data sets etc).

**Comment by svenvanderburg** [comment]
Nice investigation and really useful to see the implementation! 

I read a bit through some comparison resources ([dreamfactory blog](https://blog.dreamfactory.com/grpc-vs-rest-how-does-grpc-compare-with-traditional-rest-apis/), [google cloud blog](https://cloud.google.com/blog/products/api-management/understanding-grpc-openapi-and-rest-and-when-to-use-them), and [Sankar P medium blog](https://medium.com/@sankar.p/how-grpc-convinced-me-to-chose-it-over-rest-30408bf42794))

Some more downsides for gRPC that I distilled:
1. It is not very popular as compared to REST/openapi. If you encounter a problem it is less likely that someone else already found a solution for it.
2. gRPC-generated code has to be incorporated into client and server build processes, especially annoying when working in dynamic languages like Javascript or Python where the build process, at least on development machines, may be non-existent.

The general conclusion I got is that especially when you need a speedy, efficient communication you choose gRPC.

This together with your comparison makes my opinion sort of neutral, but given that I don't have experience with gRPC and we already have the server + client working with REST/openapi I would favour REST over gRPC.

Let's discuss in sync?

**Comment by raar1** [comment]
Yes these are very good points I should have added. There's definitely some codegen going on, but I thought the REST API building with openapi was a little bit like that. I agree that only in grpc would you need that on the client side though. I guess the tradeoff is relative to validation of types which (presumably) no longer needs to take place in the client code.

I agree with the somewhat neutral opinion. Given that we have the REST API already for niceday then let's indeed stick with that. We'll consider it for any sensor data related stuff if we build any of it ourselves.

**Comment by svenvanderburg** [comment]
Yeah, good point. Good to be aware of this. Especially with the sensor data stuff coming up!
